### PR TITLE
Add numeric compaction mode

### PR DESCRIPTION
**Pull request by Pavkazzz**
Hey, i add some compaction mode due the 2.2.4.6 paragraph of [Spec](https://www.expresscorp.com/public/uploads/specifications/44/USS-PDF-417.pdf). 
Add option on encode method `numeric_compaction`

### CODE REVIEW

**Comment by mosquito** [comment]
@ihabunek could you merge it?

**Comment by ihabunek** [comment]
I need to review, and am a little busy these days. Hope to get around to it soon.

**Comment by ihabunek** [comment]
Thanks for the contribution!

The description is a little misleading since you're not adding the numeric compaction mode, which already exists. You added an optimization to not switch to numeric mode for chunks smaller than 13 digits.

Relevant quote from the spec:
> The Numeric Compaction mode can pack almost 3 digits (2.93) into a symbol character. Though Numeric Compaction mode can be invoked at any digit length, it is recommended to use Numeric Compaction mode when there are more than 13 consecutive digits. Otherwise, use Text Compaction mode.

I want to do some tweaks on your implementation before merging, so please give a little time to do that.

**Comment by Pavkazzz** [comment]
Okey, thx

**Comment by ihabunek** [comment]
I would prefer that this optimization is not optional, but is always used. I don't see a reason not to use it, and it makes the change smaller.

There is a bug in the implementation, e.g. here is one of the tests you provided, I highlighted switch codes (900 switches to text mode and 902 to numeric mode).

```
"12345678901234 109876543210123 123 123 123",
[
    *902*, 171, 209, 269, 12, 434, 
    *900*, 809, 
    *902*, 1, 791, 564, 354, 522, 323, 
    *900*, 808, 32, 119, 
    *900*, 808, 32, 119, 
    *900*, 808, 32, 119
]
```

Notice that the last 2 switches to text mode are not needed since we already are in text mode. The implementation still works, but is not optimal.

**Comment by Pavkazzz** [comment]
Oh crab, fix it today

**Comment by Pavkazzz** [comment]
Fix

**Comment by ihabunek** [comment]
@Pavkazzz I had some time over the weekend and made a slightly neater implementation of the suggested changes (see 87b2396028e374cf0cdfa43ff45e12cf3821a93b), along with a bunch of other improvements and additional tests.

Thanks a lot for your contribution, sorry I did not merge your code. I added a mention in the [changelog](https://github.com/ihabunek/pdf417-py/blob/master/CHANGELOG.rst). Also big thanks for linking the specification, when I worked o the barcodes I could not find it. I added it to the repo.

**Comment by Pavkazzz** [comment]
> 
> 
> @Pavkazzz I had some time over the weekend and made a slightly neater implementation of the suggested changes (see [87b2396](https://github.com/ihabunek/pdf417-py/commit/87b2396028e374cf0cdfa43ff45e12cf3821a93b)), along with a bunch of other improvements and additional tests.
> 
> Thanks a lot for your contribution, sorry I did not merge your code. I added a mention in the [changelog](https://github.com/ihabunek/pdf417-py/blob/master/CHANGELOG.rst). Also big thanks for linking the specification, when I worked o the barcodes I could not find it. I added it to the repo.

Not a problem, thx

**Pull request closed without merging**
